"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import * as maplibregl from "maplibre-gl";
import type { GeoJSONSource, Map as MapLibreMap, Marker } from "maplibre-gl";
import { Anchor, ChevronLeft, Info, LandPlot, ListFilter, Menu, X } from "lucide-react";
import { EvidenceBadge } from "@/components/EvidenceBadge";
import { battles } from "@/data/battles"; import { campaignRoutes } from "@/data/campaigns"; import { historicalEvents } from "@/data/events";
import { battlesForYear } from "@/lib/historySelectors"; import { clampTimelineYear, TIMELINE_END_YEAR, TIMELINE_START_YEAR } from "@/lib/historicalDates"; import { interpolateRoutePosition, isRouteActive, splitRouteAtYear } from "@/lib/routeInterpolation";
import { eraForYear } from "@/data/wars";
import type { Battle, CampaignRoute, Faction } from "@/types/history";
import { BattlePanel } from "./BattlePanel"; import { MapLegend } from "./MapLegend"; import { TimelineControls } from "./TimelineControls";

type Filters = { rome: boolean; carthage: boolean; army: boolean; fleet: boolean; battles: boolean; sieges: boolean };
const initialFilters: Filters = { rome: true, carthage: true, army: true, fleet: true, battles: true, sieges: true };
const factionColors: Record<Faction, string> = { rome: "#a94d3e", carthage: "#2d7480" };
const rasterStyle = { version: 8 as const, sources: { carto: { type: "raster" as const, tiles: ["https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png"], tileSize: 256, attribution: "© OpenStreetMap contributors © CARTO" } }, layers: [{ id: "carto-base", type: "raster" as const, source: "carto", paint: { "raster-saturation": -0.28, "raster-contrast": -0.04 } }] };
function routeVisible(route: CampaignRoute, filters: Filters) { return filters[route.faction] && filters[route.forceType]; }
function lineCollection(routes: CampaignRoute[], year: number, filters: Filters, part: "completed" | "future") { return { type: "FeatureCollection" as const, features: routes.filter((route) => routeVisible(route, filters) && isRouteActive(route, year)).flatMap((route) => { const coordinates = splitRouteAtYear(route, year)[part]; return coordinates.length < 2 ? [] : [{ type: "Feature" as const, properties: { id: route.id, faction: route.faction, certainty: route.certainty }, geometry: { type: "LineString" as const, coordinates } }]; }) }; }

export function HistoricalMap() {
  const mapContainer = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null); const forceMarkers = useRef<Marker[]>([]); const battleMarkers = useRef<Marker[]>([]); const previousEraRef = useRef<string | undefined>(undefined);
  const [mapReady, setMapReady] = useState(false); const [year, setYear] = useState(TIMELINE_START_YEAR); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1200); const [filters, setFilters] = useState(initialFilters); const [selectedBattle, setSelectedBattle] = useState<Battle | null>(null); const [sidebarOpen, setSidebarOpen] = useState(false);
  const activeBattles = useMemo(() => battlesForYear(battles, year).filter((battle) => battle.kind === "siege" ? filters.sieges : filters.battles), [year, filters.battles, filters.sieges]); const selectedEvent = historicalEvents.find((event) => event.year === year);
  const currentEra = eraForYear(year);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setYear((current) => { if (current >= TIMELINE_END_YEAR) { setPlaying(false); return TIMELINE_END_YEAR; } return current + 1; }), speed); return () => window.clearInterval(timer); }, [playing, speed]);
  useEffect(() => {
    if (!mapContainer.current || mapRef.current) return;
    const map = new maplibregl.Map({ container: mapContainer.current, style: rasterStyle, center: [12.2, 38], zoom: 4.4, minZoom: 3.2, maxZoom: 9, attributionControl: false });
    map.addControl(new maplibregl.NavigationControl({ visualizePitch: true }), "top-right"); map.addControl(new maplibregl.AttributionControl({ compact: true }), "bottom-right");
    map.on("load", () => { map.addSource("routes-future", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); map.addSource("routes-completed", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); map.addLayer({ id: "routes-future", type: "line", source: "routes-future", paint: { "line-color": ["match", ["get", "faction"], "rome", factionColors.rome, factionColors.carthage], "line-width": 2.2, "line-opacity": 0.3, "line-dasharray": [1.5, 2.2] } }); map.addLayer({ id: "routes-completed", type: "line", source: "routes-completed", paint: { "line-color": ["match", ["get", "faction"], "rome", factionColors.rome, factionColors.carthage], "line-width": 3.2, "line-opacity": 0.88 } }); setMapReady(true); });
    mapRef.current = map; return () => { map.remove(); mapRef.current = null; };
  }, []);
  const selectBattle = useCallback((battle: Battle) => { setSelectedBattle(battle); mapRef.current?.easeTo({ center: battle.coordinates, zoom: Math.max(mapRef.current.getZoom(), 5.4), duration: 700 }); }, []);
  useEffect(() => { const map = mapRef.current; if (!mapReady || !map || !currentEra) return; if (previousEraRef.current === currentEra.id) return; previousEraRef.current = currentEra.id; if (selectedBattle) return; map.easeTo({ center: currentEra.mapView.center, zoom: currentEra.mapView.zoom, duration: 1100 }); }, [currentEra, mapReady, selectedBattle]);
  useEffect(() => {
    const map = mapRef.current; if (!mapReady || !map) return; (map.getSource("routes-completed") as GeoJSONSource)?.setData(lineCollection(campaignRoutes, year, filters, "completed")); (map.getSource("routes-future") as GeoJSONSource)?.setData(lineCollection(campaignRoutes, year, filters, "future"));
    forceMarkers.current.forEach((marker) => marker.remove()); forceMarkers.current = campaignRoutes.filter((route) => routeVisible(route, filters)).flatMap((route) => { const position = interpolateRoutePosition(route, year); if (!position) return []; const element = document.createElement("button"); element.className = `force-marker ${route.faction} ${route.forceType}`; element.textContent = route.forceType === "army" ? "▲" : "◆"; element.setAttribute("aria-label", `${route.faction === "rome" ? "Roman" : "Carthaginian"} ${route.forceType}: ${route.name}`); element.title = `${route.name} — ${route.certainty} reconstruction`; return [new maplibregl.Marker({ element, anchor: "center" }).setLngLat(position).addTo(map)]; });
    battleMarkers.current.forEach((marker) => marker.remove()); battleMarkers.current = activeBattles.map((battle) => { const element = document.createElement("button"); element.className = `battle-marker ${battle.kind} ${battle.major ? "major" : "secondary"}`; element.textContent = battle.kind === "naval" ? "≋" : battle.kind === "siege" ? "◎" : battle.kind === "campaign" ? "↟" : "⚔"; element.setAttribute("aria-label", `${battle.name}, ${battle.displayDate}. Open summary.`); element.title = `${battle.name} · ${battle.displayDate}`; element.addEventListener("click", () => selectBattle(battle)); return new maplibregl.Marker({ element, anchor: "center" }).setLngLat(battle.coordinates).addTo(map); });
  }, [activeBattles, filters, mapReady, selectBattle, year]);
  function updateYear(value: number) { const nextYear = clampTimelineYear(value); setYear(nextYear); setPlaying(false); if (selectedBattle && (nextYear < selectedBattle.startYear || nextYear > selectedBattle.endYear)) setSelectedBattle(null); }
  const filterItems: { key: keyof Filters; label: string; icon: React.ReactNode }[] = [{ key: "rome", label: "Roman forces", icon: <span className="faction-swatch rome" /> }, { key: "carthage", label: "Carthaginian forces", icon: <span className="faction-swatch carthage" /> }, { key: "army", label: "Land campaigns", icon: <LandPlot size={15} /> }, { key: "fleet", label: "Naval campaigns", icon: <Anchor size={15} /> }, { key: "battles", label: "Battles", icon: <span>⚔</span> }, { key: "sieges", label: "Sieges", icon: <span>◎</span> }];
  return <main className="atlas-shell">
    <header className="atlas-header"><div className="atlas-brand"><Link href="/" aria-label="Roman Campaign Atlas home"><span className="brand-mark">R</span><span><strong>ROMAN CAMPAIGN ATLAS</strong><small>{currentEra ? `${currentEra.shortName} · ${Math.abs(currentEra.startYear)}–${Math.abs(currentEra.endYear)} BCE` : "Roman military history"}</small></span></Link></div><div className="header-note"><Info size={15} /><span>Evidence-led reconstruction</span></div><button className="mobile-menu" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Toggle map filters">{sidebarOpen ? <X /> : <Menu />}</button></header>
    <div className="atlas-workspace"><aside className={`atlas-sidebar ${sidebarOpen ? "open" : ""}`}><div className="sidebar-heading"><span>CAMPAIGN LAYERS</span><ListFilter size={16} /></div><div className="filter-list">{filterItems.map((item) => <label key={item.key} className="filter-row"><span className="filter-label">{item.icon}{item.label}</span><input type="checkbox" checked={filters[item.key]} onChange={() => setFilters((current) => ({ ...current, [item.key]: !current[item.key] }))} /><span className="toggle" aria-hidden="true" /></label>)}</div><div className="year-events"><p className="eyebrow">YEAR IN FOCUS</p><h2>{selectedEvent?.title ?? "Campaign developments"}</h2><p>{selectedEvent?.summary ?? "The surviving sources record no major set-piece event for this year."}</p>{selectedEvent && <EvidenceBadge certainty={selectedEvent.certainty} />}</div><div className="active-list"><div className="active-list-title"><span>Visible events</span><span>{activeBattles.length}</span></div>{activeBattles.length ? activeBattles.map((battle) => <button key={battle.id} onClick={() => { selectBattle(battle); setSidebarOpen(false); }}><span className={`mini-kind ${battle.kind}`}>{battle.kind === "naval" ? "≋" : battle.kind === "siege" ? "◎" : "⚔"}</span><span><strong>{battle.name}</strong><small>{battle.location}</small></span><ChevronLeft size={15} className="event-arrow" /></button>) : <p className="empty-state">No battle marker is active. Campaign routes may still be visible.</p>}</div><p className="reconstruction-disclaimer">Ancient evidence is incomplete. Positions and routes are representative reconstructions, not exact tracks.</p></aside>
      <section className="map-stage" aria-label={`Interactive map — ${currentEra ? currentEra.name : "Roman military campaigns"}`}><div ref={mapContainer} className="map-canvas" />{!mapReady && <div className="map-loading" role="status"><span />Loading the western Mediterranean…</div>}<div className="map-caption"><span>WESTERN MEDITERRANEAN</span><small>Representative routes · modern basemap</small></div><MapLegend />{selectedBattle && <BattlePanel battle={selectedBattle} onClose={() => setSelectedBattle(null)} />}</section></div>
    <TimelineControls year={year} playing={playing} speed={speed} onYearChange={updateYear} onPlayingChange={(value) => { if (value && year === TIMELINE_END_YEAR) setYear(TIMELINE_START_YEAR); setPlaying(value); }} onSpeedChange={setSpeed} />
  </main>;
}
